<?php

namespace Database\Seeders;

use App\Models\Position;
use Illuminate\Database\Seeder;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $positions = [
            '2 / E ( MASINIS II )',
            '3 / E ( MASINIS III )',
            'ADMIN GPS',
            'ADMIN GUDANG',
            'ADMIN GUDANG SPAREPART DAN GUDANG LUB RETAIL',
            'ADMIN LEGAL&HUMAS',
            'ADMIN LUB',
            'ADMIN LUB & SOPIR',
            'ADMIN MARKETING',
            'ADMIN MINIMARKET',
            'ADMIN PLANTATION',
            'ADMIN SHIPPING',
            'ADMIN SPBU / LPG',
            'ADMIN STORAGE',
            'ADMIN TRANSPORT',
            'ADMIN TRANSPORT (MANAGEMENT TRAINEE)',
            'AMT',
            'AMT 1',
            'AMT 2',
            'ASISTEN KEBUN',
            'ASISTEN MANAGER AGRONOMI',
            'ASISTEN MANAGER AUDIT & SERTIFIKASI',
            'ASISTEN MANAGER AUDIT RETAIL & OPERATION',
            'ASISTEN MANAGER BBM INDUSTRI',
            'ASISTEN MANAGER GENERAL AFFAIR & SPBD',
            'ASMEN ACCOUNTING',
            'ASMEN ADMIN MARKETING',
            'ASMEN FINANCE',
            'ASMEN FINANCE & ACCOUNTING',
            'ASMEN HO TRANSPORT',
            'ASMEN HRD',
            'ASMEN HSE TRANSPORT',
            'ASMEN MAINTENANCE',
            'ASMEN OPERASIONAL',
            'Asmen SPBU',
            'ASMEN TRAINING DAN DEVELOPMENT',
            'ASMEN TRANSPORT',
            'ASMEN TRANSPORT WIL 1',
            'ASMEN TRANSPORT WIL 3',
            'ASSISTANT MANAGER VHS',
            'ASST. IT MANAGER',
            'ASST. KEBUN',
            'ASST.GIS',
            'BARISTA TOMORO',
            'BOATSWAIN',
            'C / E ( KKM )',
            'C/O',
            'CADET BM',
            'CADET ENGINE',
            'CHIEF OFFICER AD',
            'CHIEF OFFICER BM',
            'CHIEF OFFICER MLP',
            'CORPORATE STRATEGI',
            'DIREKTUR',
            'DIREKTUR HC & ADMIN',
            'DIREKTUR KEUANGAN',
            'DIREKTUR KOMERSIAL',
            'DIREKTUR OPERASIONAL',
            'Driver',
            'Driver Hino/ Cole 6',
            'General Manager Plantation',
            'HELPER ECAVATOR',
            'Helper Mechanic',
            'HELPER MEKANIK',
            'IT APP & DEV.',
            'Junior SPV',
            'JURU MASAK',
            'JURU MINYAK',
            'JURU MUDI',
            'JURU MUDI AD',
            'JURU MUDI BM',
            'JURU MUDI LMP',
            'Ka. Operator',
            'KASIR',
            'Kebersihan',
            'Kebersihan Rumah',
            'KEPALA ADMIN',
            'KEPALA CABANG & MANAGER MARKETING WILAYAH II',
            'Kepala Gudang',
            'Kepala Kasir Utama',
            'KERANI GUDANG',
            'KERNET LUB',
            'KKM (KEPALA KAMAR MESIN)',
            'KKM AD',
            'KOKI',
            'KOMISARIS',
            'Konsultan  Eksternal Kebun',
            'KONSULTAN PENGAWAS OPERATIONAL & PJS MANAGER AUDIT',
            'Konsultan Strategi dan Pengawas Operasional',
            'KOORDINATOR TRANSPORT (MANAGEMENT TRAINEE)',
            'KRANI ADMIN',
            'Krani Admin LPG',
            'Krani Gudang',
            'Krani Panen',
            'Management Trainee',
            'MANAGER AUIDT & SERTIFIKASI',
            'MANAGER BBM INDUSTRI WIL-1',
            'Manager FAT',
            'MANAGER HRD & GA',
            'MANAGER KEBUN',
            'MANAGER LEGAL & HUMAS',
            'MANAGER MARKETING WILAYAH V',
            'MANAGER RETAIL',
            'MANAGER SHIPPING',
            'MANAGER SPBD',
            'MANAGER TRANSPORT',
            'MANDOR PANEN',
            'MANDOR PERAWATAN',
            'Mandor Pupuk',
            'MANDOR SPRAYING',
            'MARKETING EXECUTIVE',
            'MARKETING EXECUTIVE (MANAGEMENT TRAINEE)',
            'MASINIS II',
            'MASINIS II AD',
            'MEKANIK',
            'MESSENGER',
            'MUALIM II',
            'MUALIM III',
            'NAHKODA',
            'NAHKODA AD',
            'NAHKODA LMP',
            'OFFICE BOY',
            'OFFICE GIRL',
            'OP Backhoe Loader',
            'Operator',
            'OPERATOR EXCAVATOR',
            'OPERATOR FORKLIFT',
            'Operator Jonder',
            'OPERATOR STORAGE',
            'OPERATOR VHS',
            'OWNER SURVEYOR',
            'PEMBANTU GUDANG',
            'PORT ENGINEER',
            'PRAMUNIAGA',
            'Project Manager',
            'RECEPTIONIST',
            'Sales Kaisar',
            'Sales kanvas',
            'Sales Lapangan',
            'SALES RETAIL LUB',
            'Sales Sorong',
            'Sec. Guard gudang Palopat',
            'SECOND OFFICER LMP',
            'SECURITY',
            'SENIOR MANAGER CORPORATE STRATEGY',
            'SENIOR MANAGER LUB RETAIL & INDUSTRI',
            'SENIOR MANAGER PLANTATION DAN RETAIL',
            'SENIOR MANAGER TRANSPORT',
            'SENIOR MARKETING',
            'Senior Staff Gudang Lub',
            'SPV ACCOUNTING',
            'SPV AUDIT & HSE',
            'SPV FINANCE',
            'SPV HRD',
            'SPV IT',
            'SPV LUBRICANT',
            'SPV PLANTATION',
            'SPV Retail Lubricants',
            'SPV SPBU',
            'SPV TRANSPORT',
            'SPV VHS',
            'SPV.LUB',
            'SPV/KOORD. TRANSPORT',
            'STAF ADMINISTRASI',
            'STAF AGENCY',
            'STAFF',
            'STAFF ACCOUNTING',
            'STAFF ACCOUNTING & TAX',
            'STAFF AUDIT & HSE',
            'STAFF AUDIT & SERTIFIKASI',
            'STAFF BUDGETING',
            'STAFF CREWING',
            'STAFF FINANCE',
            'STAFF GA',
            'STAFF HR-GA',
            'STAFF HRD',
            'STAFF LEGAL & HUMAS',
            'STAFF LEGAL, HUMAS, & MARKETING',
            'STAFF MAINTENANCE',
            'STAFF OPERASIONAL',
            'STAFF PROCUREMEN',
            'STAFF PROCUREMENT',
            'STAFF SPBD',
            'SUPERVISOR CONTROLLER & PA',
            'SUPERVISOR LEGAL & MARKETING',
            'SUPERVISOR MARKETING',
            'SUPERVISOR MINIMARKET',
            'SUPERVISOR PROCUREMENT',
            'SUPERVISOR TRANSPORT',
            'SUPERVISOR-LPG',
            'SUPIR',
            'SUPIR (Transport)',
            'SUPIR LUB',
            'SUPIR L200',
        ];

        foreach ($positions as $name) {
            Position::firstOrCreate(['positionName' => trim($name)]);
        }
    }
}
