version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-registry/laravel-app:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount hanya storage kalau perlu persist/log saat dev; untuk prod biasanya tak perlu mount source.
      - ./storage:/var/www/html/storage
    networks:
      - laravel
    expose:
      - "9000"

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "8080:80"   # ganti ke 80 untuk prod VM
    volumes:
      - ./public:/var/www/html/public:ro
      - ./storage:/var/www/html/storage
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel

  # Queue worker (pakai image yang sama, beda command)
  queue:
    image: your-registry/laravel-app:latest
    restart: unless-stopped
    env_file:
      - .env
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    depends_on:
      - app
    networks:
      - laravel

  # Laravel Reverb (WebSocket)
  reverb:
    image: your-registry/laravel-app:latest
    restart: unless-stopped
    env_file:
      - .env
    # Pastikan config/reverb.php sesuai env di bawah
    environment:
      REVERB_SERVER_HOST: "0.0.0.0"
      REVERB_SERVER_PORT: "6001"
    command: php artisan reverb:start --host=0.0.0.0 --port=6001
    ports:
      - "6001:6001"
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
